# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ab80722a652a75a0fcc6133f118fe445c575d1b71eb47c1e4f820a3d1d306c3fadee2a7f5781ee188a85d71bbaf3ae9291dda014539afd522f93ef4e001fa5

test:
  secret_key_base: c512d1106acf96d377ae8ce4257ca1c679a4f294e2212580ca355e56899c727fe778af70f37e4f71b7ef0ca834c4d216738423b0831032b03005198ba322620c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
